### ISSUE TITLE
大佬 我用你的这份配置 没有leader键。。。。自己改了些插件和安装路径插件全部安装成功 命令有效 

### ISSUE THREAD

**Issue by huayue369** [iamcco/dotfiles#1]

**Comment by iamcco** [comment]
不大建议使用我这个配置，我这个配置基本都是我个人习惯的配置，并且会改来改去

**Comment by huayue369** [comment]
哦哦  我拿来修改了下 觉得你的配置结构很好  摸索了一天  大致可用 只是有些个插件配置好像没启动 不知道咋回事 上面的问题已经解决了 改成全路径就可以了  lightline的配置没生效 暂时还没找到原因。。
