### ISSUE TITLE
性能问题

### ISSUE THREAD

**Issue by happysmile12321** [iamcco/dotfiles#16]
MacBook Pro (Retina, 15-inch, Mid 2015)
2.2 GHz Quad-Core Intel Core i7
16 GB 1600 MHz DDR3
Intel Iris Pro 1536 MB
终端:item2,kitty,alactiy,为什么用你的配置文件感觉vim好卡？目录非git目录，无大文件.

**Comment by iamcco** [comment]
你说的卡是哪种卡？另外并不是很推荐用我的配置，很多都是个人习惯的配置

**Comment by happysmile12321** [comment]
就是切换会普通模式时，按下Esc得要一段时间才可以变回那种块状光标。
哦，我很感谢你的配置，我已经自己有一套配置了，只是参考你的配置。
现在我的配置下仍然有同样的问题，该不会是coc的问题吧。

**Comment by iamcco** [comment]
你是不是用了 tmux，用了估计是 tmux 的问题，自己 google 一下解决方案

**Comment by happysmile12321** [comment]
ok，done!
