### ISSUE TITLE
请问emmt插件的相关调用方法是从那里引入的

### ISSUE THREAD

**Issue by lqfxz520** [iamcco/dotfiles#22]
https://github.com/iamcco/dotfiles/blob/021b836437977bd9e8ef10021f11ecc8d311985c/nvim/viml/plugins.config/coc.nvim.vim#L93
当我照着你的代码做的时候，发现调用不了emmt的相关方法。所以我很疑惑

**Comment by iamcco** [comment]
我自己搞的一个 coc 插件里面 https://www.npmjs.com/package/coc-utools
